project:
  type: website

website:
  title: "Fieldnotes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics: data export from the internet archive"
        contents:
          - text: "Data basis: sampling and structure"
            file: sites/datengrundlage.qmd
          - text: "Matching scripts files to html pages"
            file: sites/script-files-to-html-pages.qmd
      - section: "Pipeline: data processing"
        contents:
          - text: "Erl√§uterung Pipeline"
            file: sites/pipeline/pipeline.qmd
          - text: "1. db tabelle: sites - Data cleaning"
            file: sites/pipeline/data-cleaning.qmd
          - text: "Erweiterung der ersten Tabelle: second export"
            file: sites/pipeline/data-cleaning-2.qmd
          - text: "2. db-tabelle: tags"
            file: sites/pipeline/create-tags-tbl.qmd
          - text: "intermezzo: dokumentation des parsing fehlers"
            file: sites/pipeline/doc-parsing-failure-tags-tbl.qmd
          - text: "3 db tabelle: traces"
            file: sites/pipeline/create-traces-tbl.qmd
          - text: "intermezzo: zwischenschritte zur vierten tabelle"
            file: sites/pipeline/create-context-pathes.qmd
          - text: "4. db tabelle: traces context"
            file: sites/pipeline/create-traces-context-tbl.qmd
          - text: "5 db tabelle: hashes"
            file: sites/pipeline/create-traces-hashes-tbl.qmd
      - section: "Analysing: How to find commenting possibilities in HTML?"
        contents:
          - text: "Different approaches how to interpret HTML"
            file: sites/approaches.qmd
          - text: "Analyzing doctype"
            file: sites/analyzing-doctypes.qmd
          - text: "Analyzing form tags"
            file: sites/analyzing-form-tags.qmd
          - text: "Context of form tags"
            file: sites/form-context.qmd
          - text: "Analyzing script tags"
            file: sites/analyzing-script-tags.qmd
          - text: "Analyzing iframes"
            file: sites/analyzing-iframes.qmd
          - text: "Analyzing specific snippets"
            file: sites/analyzing-all-tags.qmd
          - text: "All commenting traces"
            file: sites/commenting-traces.qmd
          - text: "Context of all traces"
            file: sites/tag-context.qmd
          - text: "Understanding the Hashes"
            file: sites/understanding-hashes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


